import * as React from 'react';
import { useIntl } from 'react-intl';
import { useField, useForm } from '@strapi/strapi/admin';
import { Field, Flex, IconButton, TextInput, Typography } from '@strapi/design-system';
import { ArrowClockwise, CheckCircle, WarningCircle } from '@strapi/icons';

import { useGenerateSlugMutation, useLazyCheckSlugAvailabilityQuery } from '../../services/api';
import { getTranslation } from '../../utils/getTranslation';

interface SlugInputProps {
  name: string;
  label: string;
  required?: boolean;
  disabled?: boolean;
  documentId?: string;
}

const DEBOUNCE_MS = 400;

/**
 * Slug input generated from the menu title, similar to the UID input of the
 * content manager but backed by the plugin's own endpoints.
 */
const SlugInput = ({ name, label, required, disabled, documentId }: SlugInputProps) => {
  const { formatMessage } = useIntl();
  const { value, initialValue, error, onChange } = useField<string>(name);
  const title = useForm('SlugInput', (state) => (state.values as { title?: string }).title);
  const [generateSlug, { isLoading: isGenerating }] = useGenerateSlugMutation();
  const [checkAvailability, { data: availability, isFetching: isChecking }] =
    useLazyCheckSlugAvailabilityQuery();

  // New menus follow the title until the slug is edited by hand.
  const isAutoGenerated = React.useRef(!initialValue);

  const regenerate = React.useCallback(
    async (source?: string) => {
      const res = await generateSlug({ data: { title: source ?? '' } });

      if ('data' in res && res.data) {
        onChange(name, res.data);
      }
    },
    [generateSlug, name, onChange]
  );

  React.useEffect(() => {
    if (!isAutoGenerated.current || disabled || !title) {
      return undefined;
    }

    const timeout = setTimeout(() => regenerate(title), DEBOUNCE_MS);

    return () => clearTimeout(timeout);
  }, [title, disabled, regenerate]);

  React.useEffect(() => {
    if (!value || value === initialValue) {
      return undefined;
    }

    const timeout = setTimeout(() => checkAvailability({ value, documentId }), DEBOUNCE_MS);

    return () => clearTimeout(timeout);
  }, [value, initialValue, documentId, checkAvailability]);

  const showAvailability = Boolean(value && value !== initialValue && availability && !isChecking);

  return (
    <Field.Root name={name} error={error} required={required}>
      <Field.Label>{label}</Field.Label>
      <TextInput
        disabled={disabled}
        value={value ?? ''}
        onChange={(event: React.ChangeEvent<HTMLInputElement>) => {
          isAutoGenerated.current = false;
          onChange(name, event.target.value);
        }}
        endAction={
          <Flex gap={2}>
            {showAvailability && (
              <Flex gap={1}>
                {availability!.isAvailable ? (
                  <CheckCircle fill="success500" />
                ) : (
                  <WarningCircle fill="danger500" />
                )}
                <Typography
                  variant="pi"
                  textColor={availability!.isAvailable ? 'success600' : 'danger600'}
                >
                  {formatMessage(
                    availability!.isAvailable
                      ? { id: getTranslation('slug.available'), defaultMessage: 'Available' }
                      : { id: getTranslation('slug.unavailable'), defaultMessage: 'Unavailable' }
                  )}
                </Typography>
              </Flex>
            )}
            <IconButton
              variant="ghost"
              disabled={disabled || isGenerating}
              label={formatMessage({
                id: getTranslation('slug.regenerate'),
                defaultMessage: 'Regenerate',
              })}
              onClick={() => regenerate(title)}
            >
              <ArrowClockwise />
            </IconButton>
          </Flex>
        }
      />
      <Field.Error />
    </Field.Root>
  );
};

export { SlugInput };
